services:
  litespeed:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    container_name: litespeed
    environment:
      TZ: ${TimeZone}
      WORDPRESS_DB_HOST: ${MYSQL_HOST}:${MYSQL_PORT}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./lsws/conf:/usr/local/lsws/conf
      - ./lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./bin/container:/usr/local/bin
      - ./sites:/var/www/vhosts
      - ./logs:/usr/local/lsws/logs
    ports:
      - "7080:7080"   # SOLO admin
    expose:
      - "80"          # web interno para Traefik
    restart: always 
  redis:
    image: "redis:alpine"
    logging:
      driver: none
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always